services:
  - type: web
    name: business-scraper-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - package.json
        - server.js
        - public/**